{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Sample Password Flow OAuth2 Project",
    "description" : "This is an example of using OAuth2 Password Flow in a specification to describe security to your API.",
    "contact" : {
      "name" : "Javier Rodrigo Fonseca Leal",
      "url" : "https://portafolio-javierfonseca.netlify.app/",
      "email" : "javier_fonsi@hotmail.com"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/JAVIERFONSI_1/movies/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "security" : [ {
    "password" : [ "read", "write" ]
  } ],
  "paths" : {
    "/example" : {
      "get" : {
        "summary" : "Server example operation",
        "description" : "This is an example operation to show how security is applied to the call.",
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        }
      }
    },
    "/ping" : {
      "get" : {
        "summary" : "Server heartbeat operation",
        "description" : "This operation shows how to override the global security defined above, as we want to open it up for all users.",
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        },
        "security" : [ ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "Schema" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64"
          }
        }
      }
    },
    "securitySchemes" : {
      "password" : {
        "type" : "oauth2",
        "flows" : {
          "password" : {
            "tokenUrl" : "http://example.com/oauth/token",
            "scopes" : {
              "write" : "allows modifying resources",
              "read" : "allows reading resources"
            }
          }
        }
      }
    }
  }
}